# Generated by Django 2.2 on 2020-09-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20200921_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='averageRating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
